import assert from "node:assert/strict";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import { fileURLToPath } from "node:url";
const dom = new JSDOM("<!doctype html><body></body>");
globalThis.window = dom.window;
globalThis.document = dom.window.document;
const out = fileURLToPath(new URL("./.build/tabs-store.mjs", import.meta.url));
await build({ entryPoints: [fileURLToPath(new URL("../src/store.ts", import.meta.url))], bundle: true, format: "esm", conditions: ["browser"], outfile: out });
const s = await import(out);
let checks = 0;
const check = (value, expected, label) => { assert.deepEqual(value, expected, label); checks++; };
const text = () => s.doc.blocks.map((b) => b.text).join("\n\n");

check(s.openTabs().length, 1, "one initial scratch tab");
const a = s.openDocument("Alpha", "/a.md", { encoding: "UTF-16LE", hadBom: true });
check(s.openTabs().length, 1, "first file reuses blank scratch tab");
s.updateBlock(0, "Alpha edited");
s.setActive(0);
s.setEncodingLossy(true);
s.setSourceMode(true);
s.setTabViewProvider(() => ({ scrollTop: 240, sourceStart: 3, sourceEnd: 8 }));
s.setCaretProvider(() => 5);
const b = s.openDocument("Beta", "/b.md");
check(s.openTabs().length, 2, "second file opens separately");
check(s.doc.dirty, false, "newly opened file is clean");
check(s.doc.encoding, "UTF-8", "encoding doesn't leak");
check(s.targetBlockIndex(), -1, "format target doesn't leak");
check(s.sourceMode(), false, "new tab starts in live mode");
s.updateBlock(0, "Beta edited");
s.switchTab(a);
check(text(), "Alpha edited", "switch restores edits");
check(s.doc.dirty, true, "switch restores dirty state");
check(s.doc.encoding, "UTF-16LE", "switch restores encoding");
check(s.doc.hadBom, true, "switch restores BOM");
check(s.encodingLossy(), true, "switch restores decode warning");
check(s.sourceMode(), true, "switch restores source mode");
check(s.currentTabView(), { scrollTop: 240, sourceStart: 3, sourceEnd: 8 }, "switch restores view");
check(s.consumeCaretRequest(), 5, "switch restores caret");
s.undo();
check(text(), "Alpha", "undo belongs to A");
s.switchTab(b);
check(text(), "Beta edited", "undo didn't affect B");
s.undo();
check(text(), "Beta", "B has independent undo");
s.redo();
check(text(), "Beta edited", "B has independent redo");
s.switchTab(a);
s.redo();
check(text(), "Alpha edited", "A retained redo");
s.openDocument("stale disk version", "/b.md");
check(s.activeTabId(), b, "reopening selects existing tab");
check(text(), "Beta edited", "reopening preserves unsaved buffer");
check(s.openTabs().length, 2, "no duplicate tab");
s.markTabSaved(a, "/renamed-a.md", "Alpha edited\n");
check(s.doc.filePath, "/b.md", "async save doesn't rename active tab");
check(s.doc.dirty, true, "async save doesn't clean active tab");
check(s.getTabDocument(a).dirty, false, "async save cleans original tab");
check(s.findTabByPath("/renamed-a.md"), a, "save-as updates tab path");
s.markTabSaved(b, "/b.md", "Beta\n");
check(s.doc.dirty, true, "edits made during save stay dirty");
s.setTabExternalChange("/renamed-a.md", false);
check(s.externalChange(), null, "inactive conflicts stay off active tab");
s.switchTab(a);
check(s.externalChange(), { path: "/renamed-a.md", deleted: false }, "inactive conflict restored");
s.replaceTabDocument(b, "Reloaded Beta", "/b.md", { encoding: "UTF-8", hadBom: false });
check(text(), "Alpha edited", "background reload doesn't replace active tab");
s.switchTab(b);
check(text(), "Reloaded Beta", "background reload updated target");
s.undo();
check(text(), "Reloaded Beta", "reload resets only target history");
s.cycleTab(1);
check(s.activeTabId(), a, "next tab wraps");
s.cycleTab(-1);
check(s.activeTabId(), b, "previous tab wraps");
s.removeTab(a);
check(s.activeTabId(), b, "closing inactive tab doesn't switch");
s.removeTab(b);
check(s.openTabs().length, 1, "closing final tab leaves scratch document");
check(s.doc.filePath, null, "final close clears path");
check(text(), "", "final close clears text");
check(s.doc.dirty, false, "final close is clean");
s.undo();
check(text(), "", "final close doesn't resurrect closed edits");
const scratch = s.activeTabId();
s.openDocument("", null);
check(s.openTabs().length, 2, "new always creates another tab");
check(s.activeTabId() === scratch, false, "new tab has stable distinct ID");
const renamed = s.openDocument("Rename me", "/rename.md");
s.openDocument("Other", "/other.md");
s.retargetTabPath("/rename.md", "/moved.md");
check(s.getTabDocument(renamed).filePath, "/moved.md", "sidebar rename updates inactive tab");
check(s.doc.filePath, "/other.md", "sidebar rename leaves active tab alone");
s.retargetTabPath("/moved.md", null);
check(s.getTabDocument(renamed).dirty, true, "deleted file keeps recoverable dirty buffer");
check(s.getTabDocument(renamed).filePath, null, "deleted file prompts for new save path");
const order = () => s.openTabs().map((tab) => tab.id);
const originalOrder = order();
const activeBeforeMove = s.activeTabId();
s.updateBlock(0, "Unsaved during reorder");
s.moveTab(renamed, 0);
check(order()[0], renamed, "inactive tab moves left");
check(s.activeTabId(), activeBeforeMove, "reordering doesn't activate another tab");
check(text(), "Unsaved during reorder", "reordering preserves active buffer");
check(s.getTabDocument(renamed).dirty, true, "reordering preserves inactive dirty buffer");
s.moveTab(renamed, 999);
check(order().at(-1), renamed, "tab moves right and index clamps");
s.moveTab(activeBeforeMove, 0);
check(order()[0], activeBeforeMove, "active tab can move");
s.undo();
check(text(), "Other", "reordering preserves undo history");
s.redo();
check(text(), "Unsaved during reorder", "reordering preserves redo history");
const reordered = order();
s.moveTab(-1, 0);
s.moveTab(renamed, NaN);
check(order(), reordered, "invalid moves do not affect tabs");
check([...order()].sort(), [...originalOrder].sort(), "reordering neither duplicates nor loses tabs");
const dragOut = fileURLToPath(new URL("./.build/tabdrag.mjs", import.meta.url));
await build({ entryPoints: [fileURLToPath(new URL("../src/tabdrag.ts", import.meta.url))], bundle: true, format: "esm", outfile: dragOut });
const { tabDragPosition } = await import(dragOut);
for (const widths of [[150, 150, 150], [104, 220, 180], [220, 104, 150]]) {
  let left = 0;
  const geometry = widths.map((width, id) => { const tab = { id, left, width }; left += width; return tab; });
  for (const tab of geometry) {
    check(tabDragPosition(geometry, tab.id, -tab.left).index, 0, "every tab reaches exact left edge");
    check(tabDragPosition(geometry, tab.id, -1000).index, 0, "overshooting left remains first");
    check(tabDragPosition(geometry, tab.id, left - tab.width - tab.left).index, 2, "every tab reaches exact right edge");
    check(tabDragPosition(geometry, tab.id, 1000).index, 2, "overshooting right remains last");
  }
}
check(tabDragPosition([{ id: 1, left: 0, width: 150 }], 1, -100).index, 0, "single tab stays in place");
console.log(`${checks} tab checks passed`);
